#include "ptx.h"

void gc_ptx_init(GcPtxEmitter *e, FILE *out, const char *arch, GcDiagList *d) {
    memset(e, 0, sizeof(*e));
    e->out = out;
    e->arch = arch ? strdup(arch) : strdup("sm_86");
    e->version_major = 7;
    e->version_minor = 8;
    e->diags = d;
}

static void emit(GcPtxEmitter *e, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    for (int i = 0; i < e->indent; i++) fputs(" ", e->out);
    vfprintf(e->out, fmt, ap);
    va_end(ap);
}

static const char *ptx_type(GcType t) {
    switch (t.kind) {
        case GC_TYPE_INT32: return ".s32";
        case GC_TYPE_INT64: return ".s64";
        case GC_TYPE_FLOAT32: return ".f32";
        case GC_TYPE_FLOAT64: return ".f64";
        case GC_TYPE_FLOAT16: return ".f16";
        case GC_TYPE_POINTER: return ".u64";
        case GC_TYPE_MASK:
        case GC_TYPE_INT1: return ".pred";
        default: return ".b32";
    }
}

static void emit_header(GcPtxEmitter *e) {
    fprintf(e->out, "// Generated by GPU-COBOL %s\n", GC_VERSION_STRING);
    fprintf(e->out, ".version %d.%d\n", e->version_major, e->version_minor);
    fprintf(e->out, ".target %s\n", e->arch);
    fprintf(e->out, ".address_size 64\n\n");
}

static void emit_kernel(GcPtxEmitter *e, const GcIrKernel *k) {
    fprintf(e->out, ".visible .entry %s(\n", k->name ? k->name : "kernel");
    for (int i = 0; i < k->n_params; i++) {
        GcIrValue *p = k->params[i];
        const char *ty = ".u64";
        if (p->type.kind == GC_TYPE_FLOAT32) ty = ".f32";
        else if (p->type.kind == GC_TYPE_INT32) ty = ".s32";
        else if (p->type.kind == GC_TYPE_POINTER) ty = ".u64";
        fprintf(e->out, " .param %s param_%d%s\n",
                ty, p->id, i + 1 < k->n_params ? "," : "");
    }
    fprintf(e->out, ")\n{\n");
    e->indent = 1;

    /* register declarations (simplified) */
    emit(e, ".reg .s32 %%r<64>;\n");
    emit(e, ".reg .f32 %%f<64>;\n");
    emit(e, ".reg .u64 %%rd<32>;\n");
    emit(e, ".reg .pred %%p<16>;\n");
    emit(e, "\n");

    for (GcIrBlock *b = k->blocks; b; b = b->next) {
        emit(e, "BB_%d:\n", b->id);
        for (GcIrInst *inst = b->first; inst; inst = inst->next) {
            switch (inst->op) {
                case IR_CONST:
                    if (inst->type.kind == GC_TYPE_FLOAT32)
                        emit(e, "mov.f32 %%f%d, 0f%08X; // %g\n",
                             inst->result ? inst->result->id : 0,
                             0 /* placeholder */, inst->imm_f);
                    else
                        emit(e, "mov.s32 %%r%d, %lld;\n",
                             inst->result ? inst->result->id : 0,
                             (long long)inst->imm_i);
                    break;
                case IR_PROGRAM_ID:
                    emit(e, "mov.u32 %%r%d, %%ctaid.%c;\n",
                         inst->result ? inst->result->id : 0,
                         'x' + (inst->axis % 3));
                    break;
                case IR_LANE_ID:
                    emit(e, "mov.u32 %%r%d, %%tid.x;\n",
                         inst->result ? inst->result->id : 0);
                    break;
                case IR_LOAD:
                    emit(e, "// load\n");
                    if (inst->n_operands >= 1 && inst->result)
                        emit(e, "ld.global.f32 %%f%d, [%%rd%d];\n",
                             inst->result->id,
                             inst->operands[0] ? inst->operands[0]->id : 0);
                    break;
                case IR_STORE:
                    emit(e, "// store\n");
                    if (inst->n_operands >= 3)
                        emit(e, "st.global.f32 [%%rd%d], %%f%d;\n",
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[2] ? inst->operands[2]->id : 0);
                    else if (inst->n_operands >= 1)
                        emit(e, "st.global.f32 [%%rd%d], %%f0;\n",
                             inst->operands[0]->id);
                    break;
                case IR_BINOP:
                    if (inst->bin_op == TOK_PLUS)
                        emit(e, "add.f32 %%f%d, %%f%d, %%f%d;\n",
                             inst->result ? inst->result->id : 0,
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[1] ? inst->operands[1]->id : 0);
                    else if (inst->bin_op == TOK_MINUS)
                        emit(e, "sub.f32 %%f%d, %%f%d, %%f%d;\n",
                             inst->result ? inst->result->id : 0,
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[1] ? inst->operands[1]->id : 0);
                    else if (inst->bin_op == TOK_STAR)
                        emit(e, "mul.f32 %%f%d, %%f%d, %%f%d;\n",
                             inst->result ? inst->result->id : 0,
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[1] ? inst->operands[1]->id : 0);
                    else if (inst->bin_op == TOK_SLASH)
                        emit(e, "div.rn.f32 %%f%d, %%f%d, %%f%d;\n",
                             inst->result ? inst->result->id : 0,
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[1] ? inst->operands[1]->id : 0);
                    else if (inst->bin_op == TOK_LT)
                        emit(e, "setp.lt.s32 %%p%d, %%r%d, %%r%d;\n",
                             inst->result ? inst->result->id : 0,
                             inst->operands[0] ? inst->operands[0]->id : 0,
                             inst->operands[1] ? inst->operands[1]->id : 0);
                    else
                        emit(e, "// binop %s\n", gc_token_kind_name(inst->bin_op));
                    break;
                case IR_DOT:
                    emit(e, "// dot product (fma loop placeholder)\n");
                    emit(e, "mov.f32 %%f%d, 0f00000000;\n",
                         inst->result ? inst->result->id : 0);
                    break;
                case IR_REDUCE:
                    emit(e, "// reduction placeholder\n");
                    break;
                case IR_BARRIER:
                    emit(e, "bar.sync 0;\n");
                    break;
                case IR_RETURN:
                    emit(e, "ret;\n");
                    break;
                default:
                    emit(e, "// op %d\n", (int)inst->op);
                    break;
            }
        }
    }
    e->indent = 0;
    fprintf(e->out, "}\n\n");
}

int gc_ptx_emit_module(GcPtxEmitter *e, const GcIrModule *m) {
    if (!m) return 1;
    emit_header(e);
    for (GcIrKernel *k = m->kernels; k; k = k->next)
        emit_kernel(e, k);
    return 0;
}
